### ISSUE TITLE
Is run_start actually required for a resource?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/event-model#25]
If not, why not?

**Comment by danielballan** [comment]
Good question. The answer is no, because:

(1) Until recently, Resources didn't even _have_ a `run_start` field.
(2) We want to maintain the possibility that you might have data you generally care about  and want to track outside of the context of any specific "run".

Please reopen the issue if you think the decision needs to be discussed more or revisited.

**Comment by CJ-Wright** [comment]
Hmm ok, I was hoping that there was a way to find a resource without having the datum in hand.
